image: node:latest

stages:
  - build
  - test
  - deploy
  - cleanup

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
      - public
  when: on_success
  only:
    - master

test:
  stage: test
  script: 
    - npm run test

cleanup_job:
  stage: cleanup
  script:
    - yarn cleanup-repository after jobs
  when: always