pages:
  stage: deploy
  image: ruby:2.3
  script:
    - gem install jekyll
    - jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master
---
  layout: null
  permalink: /.well-known/acme-challenge/uD1g1nr45oXK62Wfj9Cn2UOHeVTrc47lhDeJDRhhLdA
---

5TBu788fW0tQ5EOwZMdu1Gv3e9C33gxjV58hVtWTbDM.ewlbSYgvIxVOqiP1lD2zeDKWBGEZMRfO_4kJyLRP_4U
