image: node:latest

stages:
  - build
  - test
  - deploy
  - cleanup

# Install prior to executing any npm commands
before_script:
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
      - public
  when: on_success
  only:
    variables:
      - CONTENTFUL_SPACE_ID=qvcdc8xnoiup
      - CONTENTFUL_DELIVERY_TOKEN=6903553934db4e8e564b7b24c962ac66e3cf0f9cceb6312ecb6dded606d53c9e
    refs:
    - master

test:
  stage: test
  script: 
    - npm run test

cleanup_job:
  stage: cleanup
  script:
    - yarn cleanup-repository after jobs
  when: always